### ISSUE TITLE
Question: oAuth2

### ISSUE THREAD

**Issue by GeoITwinkle** [Esri/arcgis-maps-sdk-dotnet-toolkit#354]
It seems the Challenger and SignInForm in Toolkit support username/password but not oAuth2. However, our clients may access both types of sources, so I need a challenger to handle both situations. Right now, my approach is this:
1. Follow the example to set up oAuth2 challenger (https://github.com/Esri/arcgis-runtime-samples-dotnet/tree/main/src/WPF/ArcGISRuntime.WPF.Viewer/Samples/Security/OAuth).
2. When the function CreateCredentialAsync(CredentialRequestInfo info) is called, try oAuth2 first. 
3. If oAuth2 failed, try username/password with the SignInForm.

This approach is kind of working, but not a good solution. The CredentialRequestInfo parameter does not tell whether it is oAuth2 or username/password, and both of them belong to AuthentiationType.Token enum. So, it seems I can only try both. 

Is there a better way to do it? In addition, is the Challenger and SignInForm in Toolkit going to support oAuth2 later?

Thanks.

**Comment by dotMorten** [comment]
SignInForm only deals with username/password. OAuth is performed in a browser window.
