### ISSUE TITLE
Update WeakEventListener

### ISSUE THREAD

**Issue by mstefarov** [Esri/arcgis-maps-sdk-dotnet-toolkit#365]
There is a problem with current WeakEventListener pattern: Every time its OnEventAction/OnDetachAction lambdas called an instance method or referenced something from the outer context (a local, a field, a parameter), a strong reference to "this" was captured by the lambda closure.

To fix it:
- Store a reference to "source" (object to which we subscribed) on the WeakEventListener and pass it to OnDetachAction lambdas (to unsubscribe).
- When using WeakEventListener, call methods on the "instance" parameter instead of calling on "this".

See dotnet-api issue 8679 for original report.

**Comment by nCastle1** [comment]
Fixed in PR
