### ISSUE TITLE
System.Net.Http.HttpRequestException: Unexpected status line: HTTP/1.1 304 Not Modified throwing with ArcGISHttpClientHandler+NativeHttpMessageHandler.SendAsync

### ISSUE THREAD

**Issue by boobalank-dsrc** [Esri/arcgis-maps-sdk-dotnet-toolkit#426]
An exception is thrown while calling Attachment.GetDataAsync(); for retrieves attachment's data of the Asset but not able to recreate the same issue again. issue came with android.please resolves this issue.

 Esri.ArcGISRuntime.Data.Attachment.GetDataAsync();

ArcGISHttpClientHandler+NativeHttpMessageHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken, System.Boolean isRetry)
System.Net.Http.HttpRequestException: Unexpected status line: HTTP/1.1 304 Not Modified

Nuget version used:
 Esri.ArcGISRuntime.Xamarin.Forms 100.13.0 
 Esri.ArcGISRuntime.Toolkit.Xamarin.Forms 100.13.0
 Xamarin.Forms 5.0.0.2337
 
 Device used:
 Galaxy S10+ (Android 12)

**Comment by nCastle1** [comment]
I would like to help, but I need additional information. Which Toolkit component were you using when you saw this exception? What data source/service were you using? Has this only happened once, or is it a recurring issue?
