### ISSUE TITLE
Not trimmer friendly in .NET 8

### ISSUE THREAD

**Issue by espenrl** [Esri/arcgis-maps-sdk-dotnet-toolkit#538]
Hi, I'm experiencing some issues with trimming on iOS and Android using toolkit `200.3.0`.

```
ILLink : error IL2036: Esri.ArcGISRuntime.Toolkit.Maui.Primitives.AttachmentsPopupElementView.BuildDefaultItemTemplate(): Unresolved type 'Esri.ArcGISRuntime.Toolkit.Maui.Primitives.AttachmentViewModel' in 'DynamicDependencyAttribute'.
ILLink : error IL2037: Esri.ArcGISRuntime.Toolkit.Maui.OverviewMap..cctor(): No members were resolved for 'LoadStatus' on type 'Esri.ArcGISRuntime.Mapping.Map'. 
```

#### Temporary fix
``` msbuild
<PropertyGroup>
    <NoWarn>$(NoWarn);IL2036;IL2037</NoWarn>
</PropertyGroup>
```

#### Investigation

https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/8117823c0bcb48b22e4b7b9102936557de0fd8fb/src/Toolkit/Toolkit/UI/Controls/PopupViewer/AttachmentsPopupElementView.Maui.cs#L76-L80

`AttachmentViewModel` is a private class nested inside `AttachmentsPopupElementView`. I guess the full type name is incorrect.

https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/8117823c0bcb48b22e4b7b9102936557de0fd8fb/src/Toolkit/Toolkit/UI/Controls/PopupViewer/AttachmentsPopupElementView.Maui.cs#L189-L194

I haven't investigated the second error..

**Comment by dotMorten** [comment]
Good find! You're right the full type name is incorrect for `AttachmentViewModel`. 
The other one I think it just need to change from `Map.LoadStatus` to `GeoModel.LoadStatus` https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/8117823c0bcb48b22e4b7b9102936557de0fd8fb/src/Toolkit/Toolkit.Maui/OverviewMap/OverviewMap.cs#L36
