### ISSUE TITLE
Customize behavior for PopupViewer - Open URI and open attachment

### ISSUE THREAD

**Issue by bsundsbo** [Esri/arcgis-maps-sdk-dotnet-toolkit#555]
FieldsPopupElementView and AttachmentsPopupElementView has some default behavior for opening an attachment (saves to disk) and open URL in default browser. To be able to override this property, I had to create a Custom PopupViewer, custom AttachmentsPopupElementView and a custom FieldsPopupElementView. I also had to duplicate the ControlTemplate to use these popup elements templates.

Being able to override this directly on the PopupViewer, be it add behaviors to a collection, events that are routed from the PopupElements, or some other clever easy override would be excellent.

For my scenario, I wish to open URL and attachments from within my application. If I don't override this behavior directly on PopupViewer, the default behavior of default browser or save attachment would be perfectly fine.

**Comment by dotMorten** [comment]
Looks like we actually added this to the MAUI version but not the WPF version: https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/a6ee2c2e8b217bb9eb6f62f3e3897e3b95608be8/src/Toolkit/Toolkit/UI/Controls/PopupViewer/PopupViewer.Maui.cs#L129-L163

@bsundsbo would something like this work for you?

**Comment by bsundsbo** [comment]
> Looks like we actually added this to the MAUI version but not the WPF version:
> 
> https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/a6ee2c2e8b217bb9eb6f62f3e3897e3b95608be8/src/Toolkit/Toolkit/UI/Controls/PopupViewer/PopupViewer.Maui.cs#L129-L163
> 
> @bsundsbo would something like this work for you?

@dotMorten sorry, I din't see your original message until it was closed last night. To me it appears this works for me for attachment, but it is not supported by hyperlinks in popup content so it would support only half of the use cases.

The synchronous event to async method call in the example can be a bit sticky. Fresh in my mind after some deadlock issues with `IdentifyGraphicsOverlaysAsync` for some mouseover/hover functionality when the map was in various states (Map == null || mapView.DrawStatus != Complete)

**Comment by dotMorten** [comment]
@bsundsbo I'm not quite following the issue with the event to async method.

Good point on hyperlink clicks - should probably look into adding a similar event there as well. I'll log an issue for that

**Comment by bsundsbo** [comment]
> @bsundsbo I'm not quite following the issue with the event to async method.
https://learn.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#avoid-async-void

About `async void` avoidance. The example doc on the link you sent used `async void` to start the browser with the attachment path, and that reminded me of my previous task where I had to fix a deadlock issue where MouseMove event was used with `IdentifyGraphicsOverlaysAsync` for tooltip behavior, and that froze the application when the map was in a particular state as described above. Not sure if the application freeze had to do with `async void` or issues with `IdentifyGraphicsOverlaysAsync` where it froze while waiting for the SynchronizationContext

> 
> Good point on hyperlink clicks - should probably look into adding a similar event there as well. I'll log an issue for that
Great! As mentioned in a previous task, the ability to localize (or built in localization in the toolkit) the "view" link that looks a bit odd in a Norwegian application :)

**Comment by dotMorten** [comment]
`async void` is not really the issue there. It's just as likely to happen with `async Task`. In your mouse-hover case, you're in a way asking for a blocking event that freezes the mouse while you perform the identify. Naturally that isn't a good experience, so mouse move events will continue to happen while a task is operation. It is on you to decide whether you want multiple tasks overlapping or handle some sort of queuing or ignoring. Similarly blocking a click event isn't really a good choice either (imagine you want to click all 5 attachments to start downloading them all 5 in parallel, rather than one at a time).

The only part where "async void" is a problem is that you don't really get error handling the way you expect, and thus you should try and avoid throwing in those methods without a try/catch, or you can end up with an unhandled task exception.

**Comment by dotMorten** [comment]
Good call on the [View link](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/44f8d9a21a14759e4edaf6569fcaceea7023a2a9/src/Toolkit/Toolkit/UI/Controls/PopupViewer/FieldsPopupElementView.cs#L149C20-L149C44) bit. Looks like we never added that string to [the resources](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/main/src/Toolkit/Toolkit/LocalizedStrings/Resources.resx).
