### ISSUE TITLE
BasemapGallery loading demo data in production release

### ISSUE THREAD

**Issue by espenrl** [Esri/arcgis-maps-sdk-dotnet-toolkit#566]
Hi, I have a hard time initializing `BasemapGallery.AvailableBasemaps` with a custom list of basemaps. The shown gallery is overridden by the loading of what seems to be demo data. Except for a sample app, why would one want this behavior?

PS: Not using a portal

https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/5a3260c89ffc652b921221f517e53e58c9a0d73d/src/Toolkit/Toolkit.Maui/BasemapGallery/BasemapGallery.cs#L37-L45

**Comment by dotMorten** [comment]
> The shown gallery is overridden by the loading of what seems to be demo data

Could you clarify what you mean by that? Any chance you could provide a small reproducer that demonstrates the issue?

**Comment by espenrl** [comment]
I can see I was a bit short in my description. I'll explain myself more clearly.

If I add this xaml

``` xaml
<toolkit:BasemapGallery />
```

then I get a list of maps

<img width="211" alt="image" src="https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/assets/4621581/f98ddd8b-847e-4e1a-8b85-3b3834095a02">

I would expect to get an empty basemap gallery, I expect to get nothing at all. That is what I think of as "demo basemaps". For me it is a bit unusual that a UI control loads default data.

Then I try this expecting to stop loading the "demo basemaps"

``` xaml
<toolkit:BasemapGallery Portal="{x:Null}" />
```

But it still continues loading.

Next up is 

``` xaml
<toolkit:BasemapGallery Portal="{x:Null}"
                        AvailableBasemaps="{Binding Basemaps}" />
```

``` csharp
public MapPageViewModel()
{
    LoadBasemapGallery();
}

private async void LoadBasemapGallery()
{
    var aTask = BasemapGalleryItem.CreateAsync(new Basemap(new ArcGISTiledLayer(new Uri(Constants.GeodataServiceUri.Bilder))));
    var bTask = BasemapGalleryItem.CreateAsync(new Basemap(new ArcGISTiledLayer(new Uri(Constants.GeodataServiceUri.VectorNordenBasisTerreng))));
    var cTask = BasemapGalleryItem.CreateAsync(new Basemap(new ArcGISTiledLayer(new Uri(Constants.GeodataServiceUri.VectorNordenGråtoneTerreng))));

    await Task.WhenAll(aTask, bTask, cTask);

    Basemaps.Add(aTask.Result);
    Basemaps.Add(bTask.Result);
    Basemaps.Add(cTask.Result);
}

public ObservableCollection<BasemapGalleryItem> Basemaps { get; } = new();
```

But it still continues to load the "demo basemaps" and I can't get it to show my custom basemaps definition.

At this point I looked up the source code

https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/5a3260c89ffc652b921221f517e53e58c9a0d73d/src/Toolkit/Toolkit.Maui/BasemapGallery/BasemapGallery.cs#L37-L45

..and discovered that the loading of initial "demo basemaps" are triggered from the constructor regardless of anything else. For apps that don't use this initial setup of basemaps I think that is a bit unfortunate. It also leads to many `ArcGISWebException` because of missing `ChallengeHandler` setup, thus slowing down app startup.
