### ISSUE TITLE
PopupViewer: Allow overriding URL clicks

### ISSUE THREAD

**Issue by dotMorten** [Esri/arcgis-maps-sdk-dotnet-toolkit#576]
Currently if you click a link in the popup viewer it'll open the default browser. In some cases you might want to just open the link in a webview inside the app.
We should provide a [similar approach as with attachment clicks](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/blob/ae34e71ba4bf81ff6c57d178c26cf53dd89bf8a9/src/Toolkit/Toolkit/UI/Controls/PopupViewer/PopupViewer.cs#L239-L273), allowing users to cancel the default operation and perform their own.

Follow-up to issue #555 suggested by @bsundsbo

**Comment by prathameshnarkhede** [comment]
This feature will be available in v200.5
